# ==========================================
# Root Outputs Definition
# Outputs expose information about the infrastructure that Terraform just built.
# Here we take the complex outputs generated by our child modules and simply 
# bubble them up to the root level so they print to the console when `terraform apply` finishes.
# ==========================================

output "divisions" {
  description = "Consolidated details (IDs and Names) of all created Divisions"
  value       = try(module.divisions[0].division_details, {})
}

output "skills" {
  description = "Consolidated details (IDs and Names) of all created Routing Skills"
  value       = try(module.skills[0].skill_details, {})
}

output "queues" {
  description = "Consolidated details (IDs and Names) of all created Routing Queues"
  value       = try(module.queues[0].queue_details, {})
}

output "users" {
  description = "Consolidated details (IDs and Names) of all created Users"
  value       = try(module.users[0].user_details, {})
}

output "roles" {
  description = "Consolidated details (IDs and Names) of all created Authorization Roles"
  value       = try(module.roles[0].role_details, {})
}

